<!--/**-->
<!--* @category NaumovExtensions-->
<!--* @package NaumovExtensions_InventoryManagement-->
<!--* @author Anton Naumov <anton2-2000@mail.ru>-->
<!--* @copyright Copyright (c) 2023 NaumovExtensions-->
<!--*/-->
<table class="table">
    <tbody>
    <tr>
        <th><?= __('Product ID') ?></th>
        <td><?= $block->escapeHtml($block['details']['product_id']) ?></td>
    </tr>
    </tbody>
</table>

